---
# Source: sbi-cms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sbi-cms-issuance-card-management-extn
  namespace: sbi
  labels:
    app: sbi-cms-issuance-card-management-extn
  annotations: 
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8063-8063'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 8063
      targetPort: 8063
      name: 8063-8063
  selector:
    app: sbi-cms-issuance-card-management-extn
  type: ClusterIP
