---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-global-service
data:
  MYSQL_HOST: "192.168.1.236"
  ALLOWED_ORIGINS: "https://dcms.apps.dcmsnonprod.bank.sbi,http://localhost:4200"
  CMS_USER_ACCESS_MANAGEMENT_API: "http://sbi-cms-user-access-management-extn:7070/sbi/uam/v2"
  GLOBAL_DATA_SCHEMA: "CMS_GLOBAL"
  JASYPT_PASSWORD: "cmsblaze"
  ORACLE_HOST: "uatrac-scan.dcmsnonprod.bank.sbi"
  ORACLE_PASSWORD: "Kv3Cf951"
  ORACLE_PORT: "6521"
  ORACLE_SERVICE_NAME: "DCMSDB"
  ORACLE_USER: "blaze"
  POSTGRES_HOST: "globaldb-preprod-platform-cms-rds.global-g9jpjqjqn9ip.global.rds.amazonaws.com"
  POSTGRES_PASSWORD: "preprodcms123#"
  POSTGRES_USER: "postgres"
  SCHEMA: "CMS_GLOBAL"
  SYSTEM_USER: "SYSTEM_USER"
  TOKEN_EXPIRY: "24m"
  TOKEN_SIGNING_KEY: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb"
