---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-platform-audit-service
data:
  MYSQL_HOST: "192.168.1.236"
  KAFKA_HOST: "dcms.apps.dcmsnonprod.bank.sbi"
  KAFKA_PORT: "9092"
  ACTIVE_DB_PROFILE: "oracle"
  ALERT_APPLICABLE: "1"
  ALLOWED_ORIGINS: "https://dcms.apps.dcmsnonprod.bank.sbi,http://localhost:4200"
  AUDIT_SCHEMA: "CMS_AUDIT"
  BLAZE_INTEGRATOR_API_URL: "http://kvb-cms-mapping:8080/kvb-mapping"
  CMS_ALERT_API: "http://sbi-cms-issuance-scheduler-api-extn:8056/sbi/scheduler-api"
  CMS_BATCH_SCHEDULER_API: "http://sbi-cms-issuance-batch-scheduler-extn:8058/sbi/issuance-batch-scheduler"
  CMS_CARD_ISSUANCE_SCHEMA: "CMS_CARD"
  CMS_CARD_MANAGEMENT_API: "http://sbi-cms-issuance-card-extn:8063/sbi/card-management/card_management"
  CMS_HSM_CONNECT_API: "http://sbi-cms-issuance-hsm-connect-extn:8062/sbi/hsm-connector"
  CMS_PROGRAM_API: "http://sbi-cms-issuance-program-configuration-extn:8091/sbi/program-config/program_configuration"
  CMS_SCHEDULER_API: "http://sbi-cms-issuance-scheduler-api-extn:8056/sbi/scheduler-api"
  CMS_SUPPORT_API: "http://sbi-cms-issuance-support-extn:8057/sbi/issuance-support/support"
  CMS_USER_ACCESS_MANAGEMENT_API: "http://sbi-cms-user-access-management-extn:7070/sbi/uam/v2"
  GLOBAL_SERVICE_API: "http://sbi-cms-global-service:8050/sbi/global-service"
  HASH_ALGORITHM: "HmacSHA256"
  HASH_KEY: "9XRe0/lWYrDzmWQhAdrLKQK3JY/O125wZahPsMRPr/c="
  JASYPT_PASSWORD: "cmsblaze"
  KEY_ENC_KEY: "S5V8csbx5DR3turpLQErNk3GXP1szQsfDpoqlUju6Y4="
  MYSQL_HOST: "192.168.1.236"
  MYSQL_PASSWORD: "Canaraprod#123"
  MYSQL_SCHEMA_PREFIX: ""
  MYSQL_USER: "admin"
  NPCI_PRIVATEKEY_FILE: "/data/npci_privatekey.pem"
  NPCI_PUBLICKEY_FILE: "/data/npci_publickey.pem"
  ORACLE_HOST: "uatrac-scan.dcmsnonprod.bank.sbi"
  ORACLE_PASSWORD: "Kv3Cf951"
  ORACLE_SCHEMA_PREFIX: ""
  ORACLE_USER: "blaze"
  POSTGRES_HOST: "globaldb-preprod-platform-cms-rds.global-g9jpjqjqn9ip.global.rds.amazonaws.com"
  POSTGRES_PASSWORD: "preprodcms123#"
  POSTGRES_SCHEMA_PREFIX: ""
  POSTGRES_USER: "postgres"
  SECURITY_ASYMMETRIC_PRIVATEKEY_FILE: "/config/privatekey.asc"
  SECURITY_ASYMMETRIC_PUBLICKEY_FILE: "/config/publickey.asc"
  SYSTEM_USER: "SYSTEM_USER"
  TOKEN_EXPIRY: "24m"
  TOKEN_SIGNING_KEY: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb"
  VISA_PRIVATEKEY_FILE: "/data/visa_privatekey.pem"
  VISA_PUBLICKEY_FILE: "/data/visa_publickey.pem"
