---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-issuance-ui-app
data:
  ALERT_APPLICABLE: "1"
  CMS_COMMON_BASE_URL: "https://dcms.apps.dcmsnonprod.bank.sbi"
  CMS_SECRET_KEY: "your-16-byte-key"
  GO_CONNECT_BASE_URL: "http://a6207894b32a949f2a124b2a9cabbfc8-cd7e170a6d02d5c5.elb.ap-south-1.amazonaws.com"
  GO_CONNECT_JAVA_URL: "/sbi/javaconnect"
  GO_CONNECT_SERVER_URL: "/sbi/go-connect-base24-classic-d1"
  HIDE_PRODUCT_FEATURE: "0"
