---
# Source: sbi-cms/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sbi-cms-issuance-ui-app
  namespace: sbi
spec:
  scaleTargetRef:
    kind: Deployment
    name: sbi-cms-issuance-ui-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 100
