---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-platform-dev-gc-base24-classic-f1
data:
  MYSQL_HOST: "192.168.1.236"
  KAFKA_HOST: "dcms.apps.dcmsnonprod.bank.sbi"
  KAFKA_PORT: "9092"
  ALERT_APPLICABLE: "1"
  APP_CONTEXT_PATH: "/sbi/go-connect-base24-classic-f1"
  APP_COPYRIGHT: "© 2023 Financial Software and Systems"
  APP_DESC: "This application will connect on TCP Protocol with other application. This is written in GO."
  APP_ENV: "uat"
  APP_NAME: "GO-CONNECT-CLIENT"
  CA_CERT_PATH: "/sbi/gc-ca-cert.pem"
  CA_CERT_PROVIDER_SERVER: "localhost"
  CLIENT_CERT_PATH: "/sbi/gc-client-cert.pem"
  CLIENT_KEY_PATH: "/sbi/gc-client-key.pem"
  CONNECTION_NAME: "BASE24-CLASSIC-F1"
  CONNECT_RETRY_ATTEMPTS: "3"
  CONNECT_RETRY_INTERVAL: "3"
  DATASOURCE_DB: "DCMSDB"
  DATASOURCE_DBTYPE: "oracle"
  DATASOURCE_HOST: "uatrac-scan.dcmsnonprod.bank.sbi"
  DATASOURCE_PASSWORD: "zK402UAb"
  DATASOURCE_PORT: "6521"
  DATASOURCE_SCHEMA: "GO_CONNECT"
  DATASOURCE_USERNAME: "GO_CONNECT"
  DB_SSL_MODE: "disable"
  GOCONNECT_PRODUCT_LIST_URL: "http://sbi-cms-global-service.sbi.svc.cluster.local:8050"
  INSECURE_MODE: "true"
  IS_ENC_REQUEST_RESPONSE: "N"
  IS_ISO_HEADER_REQUIRED: "Y"
  IS_MASK: "N"
  IS_REDIS_AVLBL_FOR_LOCKING: "N"
  JASYPT_PASSWORD: "cmsblaze"
  NATS_ALT_TOPIC_SUFFIX: ".ALT"
  NATS_CONNECTION_URL: "nats-cluster.nats-cluster.svc.cluster.local:4222"
  OTEL_EXPORTER_OTLP_ENDPOINT: "k8s-observab-observab-ee0ff946f0-987421e67184d9e0.elb.ap-south-1.amazonaws.com:4317"
  OTEL_SERVICE_NAME: "GO_CONNECT"
  PORT: "8290"
  PRODUCT_APP_URL: "http://sbi-cms-issuance-card-extn:8061/sbi/card-issuance/card/communicationControllerJavaConnect/getcardactivationdata"
  PRODUCT_CODE: "CMS001"
  REDIS_HOST: "sbi-cms-infinispan.openshift-operators.svc.cluster.local"
  REDIS_PORT: "6379"
  SECURITY_SYMMETRIC_ENCDEC_CIPHER_ALGORITHM: "AES/GCM/NoPadding"
  SECURITY_SYMMETRIC_ENCDEC_KEY: "1mK2eULaFN/CGVDEetVkxY1ZCto/42ziSSGTVNLQwnA="
  SECURITY_SYMMETRIC_ENCDEC_KEY_ALGORITHM: "AES"
  SERVICE_API_KEY: "WIpuwd7flpwKbgw1I2I0qMZz2H1kovb+fCOSA5nJlaM="
  SERVICE_NAME: "go-connect"
  TENANT_CODE: "SBI"
  UAM_API_DNS: "sbi-cms-user-access-management-extn:7070"
  UAM_API_ENDPOINT: "/sbi/uam/v2/user/authorize"
  UAM_API_PROTOCOL: "http"
  UAM_CHECK_REQUIRED: "false"
  USE_TLS: "Y"
