---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-user-management-extn
data:
  MYSQL_HOST: "192.168.1.236"
  KAFKA_HOST: "dcms.apps.dcmsnonprod.bank.sbi"
  KAFKA_PORT: "9092"
  ACTIVE_DB_PROFILE: "oracle"
  ALERT_APPLICABLE: "1"
  ALLOWED_ORIGINS: "https://dcms.apps.dcmsnonprod.bank.sbi,http://localhost:4200"
  CMS_ALERT_API: "http://sbi-cms-issuance-scheduler-api-extn:8056/sbi/scheduler-api"
  CMS_PROGRAM_API: "http://sbi-cms-issuance-program-configuration-extn:8091/sbi/program-config/program_configuration"
  CMS_USER_ACCESS_MANAGEMENT_API: "http://sbi-cms-user-access-management-extn:7070/sbi/uam/v2"
  CMS_USER_MANAGEMENT_SCHEMA: "CMS_USER_ADMIN"
  HASH_ALGORITHM: "HmacSHA256"
  HASH_KEY: "9XRe0/lWYrDzmWQhAdrLKQK3JY/O125wZahPsMRPr/c="
  JASYPT_PASSWORD: "cmsblaze"
  KAFKA_STATUS: "no-kafka"
  MYSQL_HOST: "192.168.1.236"
  MYSQL_PASSWORD: "Canaraprod#123"
  MYSQL_SCHEMA_PREFIX: ""
  MYSQL_USER: "admin"
  ORACLE_HOST: "uatrac-scan.dcmsnonprod.bank.sbi"
  ORACLE_PASSWORD: "Kv3Cf951"
  ORACLE_PORT: "6521"
  ORACLE_SCHEMA_PREFIX: ""
  ORACLE_SERVICE_NAME: "DCMSDB"
  ORACLE_USER: "blaze"
  PASSWORD_RESET_LINK: "https://devcms.np.fssblaze.com/sbi/resetpassword?token="
  POSTGRES_HOST: "globaldb-preprod-platform-cms-rds.global-g9jpjqjqn9ip.global.rds.amazonaws.com"
  POSTGRES_PASSWORD: "preprodcms123#"
  POSTGRES_SCHEMA_PREFIX: ""
  POSTGRES_USER: "postgres"
  SCHEMA: "CMS_USER_ADMIN"
  SYSTEM_USER: "SYSTEM_USER"
  TOKEN_EXPIRY: "24m"
  TOKEN_SIGNING_KEY: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb"
