---
# Source: sbi-cms/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbi-cms-platform-go-connect
  namespace: sbi
  labels:
    app: sbi-cms-platform-go-connect
    intent: apps
spec:
  selector:
    matchLabels:
      app: sbi-cms-platform-go-connect
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sbi-cms-platform-go-connect
        intent: apps
      annotations:
        kubernetes.io/psp: eks.privileged
        "fss.com/app-configmap-hash": 13fcf1deee0a391e282b10e8944ebc26672e58fc059999e2988a2896ed5d5264
    spec:
      serviceAccountName: sbi-cms-platform-go-connect-sa
      volumes:
      containers:
        - name: sbi-cms-platform-go-connect
          image: 736483234466.dkr.ecr.ap-south-1.amazonaws.com/sbi-cms-platform-go-connect:sbi-uat.v81
          volumeMounts:
          ports:
            - containerPort: 8290
              protocol: TCP
            - containerPort: 8680
              protocol: TCP
          envFrom:
            - configMapRef:
                name: sbi-cms-platform-go-connect
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      nodeSelector:
        app: sbi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
