---
# Source: sbi-cms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sbi-cms-platform-go-connect
  namespace: sbi
  labels:
    app: sbi-cms-platform-go-connect
  annotations: 
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8290-8290'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 8290
      targetPort: 8290
      name: 8290-8290
    - protocol: TCP
      port: 8680
      targetPort: 8680
      name: 8680-8680
  selector:
    app: sbi-cms-platform-go-connect
  type: ClusterIP
