---
# Source: sbi-cms/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbi-cms-mapping-sa
  namespace: sbi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::903304317280:role/s3_cms_role
