apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ tpl .Values.deployment.namespace $ }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.deployment.name }}
    apiVersion: apps/v1
  minReplicas: {{ tpl .Values.hpa.minReplicas $ }}
  maxReplicas: {{ tpl .Values.hpa.maxReplicas $ }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 100
