{{- if and (eq .Values.route.required true) (eq .Values.environment.env_name "uat") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ tpl .Values.deployment.namespace . }}
spec:
  host: a6207894b32a949f2a124b2a9cabbfc8-cd7e170a6d02d5c5.elb.ap-south-1.amazonaws.com 
  path: {{ .Values.route.path | quote }}
  to:
    kind: Service
    name: {{ .Values.deployment.name }}
  port:
    targetPort: {{ .Values.route.targetPort }}
{{- end }}