{{ if eq .Values.serviceAccount.required true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.name }}-sa
  namespace: {{ tpl .Values.deployment.namespace $ }}
  annotations:
    eks.amazonaws.com/role-arn: {{ tpl .Values.serviceAccount.roleARN $ }}
{{ end }}
