---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-platform-java-connect
data:
  MYSQL_HOST: "192.168.1.236"
  KAFKA_HOST: "dcms.apps.dcmsnonprod.bank.sbi"
  KAFKA_PORT: "9092"
  ALERT_APPLICABLE: "1"
  CONTEXT_PATH: "/sbi/javaconnect"
  DATASOURCE_DIALECT: "org.hibernate.dialect.OracleDialect"
  DATASOURCE_DRIVER: "oracle.jdbc.driver.OracleDriver"
  DATASOURCE_PASSWORD: "zK402UAb"
  DATASOURCE_SCHEMA: "GO_CONNECT"
  DATASOURCE_URL: "jdbc:oracle:thin:@uatrac-scan.dcmsnonprod.bank.sbi:6521/DCMSDB"
  DATASOURCE_USERNAME: "GO_CONNECT"
  GOCONNECT_PRODUCT_LIST_URL: "http://sbi-cms-global-service.sbi.svc.cluster.local:8050"
  JASYPT_PASSWORD: "cmsblaze"
  NATS_CONNECTION_URL: "nats-cluster.nats-cluster.svc.cluster.local:4222"
  SERVICE_ACCESS_KEY: "WIpuwd7flpwKbgw1I2I0qMZz2H1kovb+fCOSA5nJlaM="
  SERVICE_ACCESS_NAME: "java-connect"
  UAM_API_DNS: "sbi-cms-user-access-management-extn:7070"
