---
# Source: sbi-cms/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbi-cms-platform-go-exchange-rate-mapper
data:
  APP_CONTEXT_PATH: "/sbi/platform/go-exchange-rate-mapper"
  APP_COPYRIGHT: "© 2023 Financial Software and Systems"
  APP_DESC: "This application will connect on TCP Protocol with other application. This is written in GO."
  APP_ENV: ""
  APP_NAME: "GO-EXCHNAGE-RATE-MAPPER"
  CA_CERT_PATH: "/sbi/gc-ca-cert.pem"
  CLIENT_CERT_PATH: "/sbi/gc-client-cert.pem"
  CLIENT_KEY_PATH: "/sbi/gc-client-key.pem"
  DATASOURCE_DB: "DCMSDB"
  DATASOURCE_DBTYPE: "oracle"
  DATASOURCE_HOST: "uatrac-scan.dcmsnonprod.bank.sbi"
  DATASOURCE_PASSWORD: "zK402UAb"
  DATASOURCE_PORT: "6521"
  DATASOURCE_SCHEMA: "GO_CONNECT"
  DATASOURCE_USERNAME: "GO_CONNECT"
  DB_SSL_MODE: "disable"
  INSECURE_MODE: "true"
  IS_MASK: "N"
  JASYPT_PASSWORD: "cmsblaze"
  NATS_CONNECTION_URL: "nats-cluster.nats-cluster.svc.cluster.local:4222"
  OTEL_EXPORTER_OTLP_ENDPOINT: "k8s-observab-observab-ee0ff946f0-987421e67184d9e0.elb.ap-south-1.amazonaws.com:4317"
  OTEL_SERVICE_NAME: "GO_EXCHANGE_RATE_MAPPER"
  PORT: "5522"
  SECURITY_SYMMETRIC_ENCDEC_CIPHER_ALGORITHM: "AES/GCM/NoPadding"
  SECURITY_SYMMETRIC_ENCDEC_KEY: "1mK2eULaFN/CGVDEetVkxY1ZCto/42ziSSGTVNLQwnA="
  SECURITY_SYMMETRIC_ENCDEC_KEY_ALGORITHM: "AES"
  SERVICE_API_KEY: "WIpuwd7flpwKbgw1I2I0qMZz2H1kovb+fCOSA5nJlaM="
  SERVICE_NAME: "go-exchange-rate-mapper"
  UAM_API_DNS: ""
  UAM_API_ENDPOINT: ""
  UAM_API_PROTOCOL: ""
  UAM_CHECK_REQUIRED: "false"
  USE_TLS: "Y"
